In [1]:
import numpy as np

In [12]:
arr=np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x=np.arange(1,9).reshape(2,4)

In [34]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
x=np.array([2,4,6,])
x

array([2, 4, 6])

In [44]:
x[2]

6

In [46]:
a=np.array([2,5,6])

In [48]:
a[1]

5

In [50]:
a[0]=4

In [52]:
a

array([4, 5, 6])

Task

create array 5 values

1- print 3rd value

2- edit 4th value with 55

In [65]:
ar=np.array([2,5,3,8,9])
ar

array([2, 5, 3, 8, 9])

In [67]:
ar[2]

3

In [74]:
ar[3]=55
ar

array([ 2,  5,  3, 55,  9])

In [96]:
m=np.array([[2,5,7,],
            [6,3,9]])
m


array([[2, 5, 7],
       [6, 3, 9]])

In [98]:
(m[0,1])

5

In [100]:
(m[1,2])

9

In [102]:
m.shape

(2, 3)

In [110]:
(m[0,2], m[1,0])

(7, 6)

Task

create array 2D

3 row 3 col

1- print 1st row

2- print 1st col

3- print element row 2 col 2

4- edit element row 3 col 3 value with 55

In [147]:
r=np.array([[22,54,6],
          [21,21,33],
          [55,7,6]])
r

array([[22, 54,  6],
       [21, 21, 33],
       [55,  7,  6]])

In [149]:
r[0]

array([22, 54,  6])

In [151]:
r[:,0]

array([22, 21, 55])

In [153]:
r[1,1]

21

In [155]:
r[2,2]=44

In [157]:
r

array([[22, 54,  6],
       [21, 21, 33],
       [55,  7, 44]])

In [159]:
z=np.zeros([2,2])

In [161]:
z

array([[0., 0.],
       [0., 0.]])

In [167]:
o=np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [175]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [179]:
f=np.full((3,3),5)
f

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [183]:
r=np.random.random((2,2))
r

array([[0.76764977, 0.78294328],
       [0.37701216, 0.42560675]])

In [191]:
t=np.random.randint(low=2,high=20,size=(4,4))
t

array([[19, 10,  6, 15],
       [ 2,  7,  9,  5],
       [17,  8,  5, 14],
       [15,  7, 15, 18]])

Task

create a ticket system chocess random between 141 fan

every time we choose 4 fans

In [198]:
fans=np.random.randint(low=1,high=142,size=(4))
fans

array([ 37, 127, 132,  26])

Array indexing

In [205]:
y=np.random.randint(low=1,high=60,size=(3,4))
y

array([[44, 41, 48, 43],
       [34,  6, 39, 27],
       [44, 33, 25, 26]])

In [211]:
y[2,2]

25

In [215]:
y[0:2 ,0:2]

array([[44, 41],
       [34,  6]])

In [217]:
(y[y>40])

array([44, 41, 48, 43, 44])

In [219]:
b=[y>40]

In [221]:
b

[array([[ True,  True,  True,  True],
        [False, False, False, False],
        [ True, False, False, False]])]

Task

1- create function takes two arrays >>>> size of array (3,3)

2- print multiply two arrays

3- print subtract 2 arrays

4- return sub array size 2,2 from result of multiply

In [244]:
def arr(x1,x2):
    print('Multi')
    print(np.multiply(x1,x2))
    print('sum')
    print(np.add(x1,x2)) 
    print('substract')
    print(np.subtract)
    multi=np.multiply(x1,x2)

    return(multi[1:3,1:3])  

In [246]:
arr1=np.random.randint(low=2,high=50,size=(3,3))
arr2=np.random.randint(low=3,high=60,size=(3,3))

In [248]:
arr(arr1,arr2)

Multi
[[ 819   75  616]
 [1058  285  462]
 [ 350 1092 1848]]
sum
[[60 28 58]
 [69 34 47]
 [39 68 86]]
substract
<ufunc 'subtract'>


array([[ 285,  462],
       [1092, 1848]])

In [250]:
v = np.array([9,10])
w = np.array([11, 12])

In [252]:
v

array([ 9, 10])

In [254]:
w

array([11, 12])

In [256]:
(v.dot(w))

219

In [264]:
x=np.arange(1,17).reshape(4,4)
print(x)
np.sum(x,axis =1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([10, 26, 42, 58])